/* Auto-generated by export_weights.py — do NOT edit manually */
#pragma once
#include <stdint.h>

#define SNN_HIDDEN              32
#define SNN_DELTA_THRESH        0.1000f
#define SNN_THRESH1             0.1000f
#define SNN_DECISION_INTERVAL   50
#define SNN_IDLE_RATE_THRESH    0.15f   // hidden_rate below this = motor stopped = anomaly

static const float SNN_BETA1 = 0.511756f;

/* FC1 weights — [HIDDEN]  streaming: one weight per hidden neuron */
/* [32]  row-major */
static const float SNN_W1[32] = {
    -0.515709f, -0.515229f, -0.073923f, -0.883770f, -0.216241f, 0.723239f, -0.377459f, 0.030439f,
    0.190449f, -0.007998f, -0.387737f, -1.019163f, -0.062133f, 1.041578f, -0.123128f, 0.460739f,
    -0.581378f, -0.622489f, -0.406995f, 0.873292f, -0.278702f, -0.277859f, 0.118024f, -0.254405f,
    -0.843063f, -0.244387f, 0.030507f, -0.169733f, -0.071090f, -0.563394f, -0.067830f, -0.917989f
};

/* FC2 weights — [2 × HIDDEN]  linear output */
/* [2×32]  row-major */
static const float SNN_W2[64] = {
    -0.116290f, -0.068809f, 0.147257f, -0.129158f, 0.012945f, 0.075093f, 0.083138f, -0.046241f,
    -0.140410f, 0.026140f, 0.169807f, 0.011706f, -0.106835f, -0.087431f, 0.064122f, 0.113798f,
    -0.052698f, 0.078326f, 0.163851f, 0.077673f, 0.063763f, -0.015857f, 0.049961f, 0.090873f,
    0.099680f, 0.152417f, 0.056973f, -0.006631f, 0.019727f, -0.068441f, 0.007310f, 0.145728f,
    0.158287f, -0.114345f, 0.160230f, 0.068804f, -0.136668f, -0.081753f, -0.073109f, -0.042175f,
    0.022600f, 0.020630f, 0.028415f, -0.128289f, -0.118838f, 0.185044f, -0.037334f, -0.097936f,
    0.068995f, -0.086859f, -0.141598f, 0.111150f, -0.025893f, -0.059752f, 0.139825f, 0.165965f,
    0.139304f, 0.029712f, 0.062340f, 0.152814f, 0.031262f, -0.024253f, -0.008412f, -0.017359f
};

