"""
Export trained SNN weights to a C header for ESP32 on-device inference.

Usage
-----
  python export_weights.py                         # reads model.pth
  python export_weights.py --model model.pth       # explicit path

Output
------
  firmware/include/snn_weights.h   — static const float arrays + #define macros
"""

import argparse
import pathlib
import textwrap

import torch

MODEL_PATH  = pathlib.Path("model.pth")
HEADER_PATH = pathlib.Path("../firmware/include/snn_weights.h")


# ── Helpers ───────────────────────────────────────────────────────────────────

def tensor_to_c_array(name: str, t: torch.Tensor) -> str:
    """Render a tensor as a C static const float array (row-major)."""
    flat   = t.detach().cpu().float().numpy().flatten()
    values = ", ".join(f"{v:.6f}f" for v in flat)
    shape  = "×".join(str(d) for d in t.shape)
    body   = textwrap.fill(
        values, width=100,
        initial_indent="    ", subsequent_indent="    "
    )
    return (
        f"/* [{shape}]  row-major */\n"
        f"static const float {name}[{flat.size}] = {{\n"
        f"{body}\n"
        f"}};\n"
    )


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Export SNN weights to C header")
    parser.add_argument("--model",  default=str(MODEL_PATH),  help="Path to model.pth")
    parser.add_argument("--output", default=str(HEADER_PATH), help="Output header path")
    args = parser.parse_args()

    model_path  = pathlib.Path(args.model)
    header_path = pathlib.Path(args.output)

    if not model_path.exists():
        raise FileNotFoundError(
            f"Model not found: {model_path}\n"
            "Train first:  python train_snn.py"
        )

    ckpt  = torch.load(model_path, map_location="cpu", weights_only=True)
    state = ckpt["model_state"]
    cfg   = ckpt["config"]

    streaming = cfg.get("mode") == "streaming"
    w2    = state["fc2.weight"]          # [2, HIDDEN]
    beta1 = float(state["lif1.beta"])

    if streaming:
        # fc1.weight is [HIDDEN, 1] — squeeze to [HIDDEN] vector
        w1 = state["fc1.weight"].squeeze(1)
        print(f"  Mode    : streaming  (one spike/step, no fixed window)")
        print(f"  W1 : {tuple(w1.shape)}   W2 : {tuple(w2.shape)}")
        print(f"  Beta1={beta1:.4f}  decision_interval={cfg['decision_interval']}")
        print(f"  Flash footprint : {(w1.numel() + w2.numel()) * 4 / 1024:.2f} KB (float32)")
        lines = [
            "/* Auto-generated by export_weights.py — do NOT edit manually */",
            "#pragma once",
            "#include <stdint.h>",
            "",
            f"#define SNN_HIDDEN              {w1.shape[0]}",
            f"#define SNN_DELTA_THRESH        {cfg['delta_thresh']:.4f}f",
            f"#define SNN_THRESH1             {cfg['threshold']:.4f}f",
            f"#define SNN_DECISION_INTERVAL   {cfg['decision_interval']}",
            "",
            f"static const float SNN_BETA1 = {beta1:.6f}f;",
            "",
            "/* FC1 weights — [HIDDEN]  streaming: one weight per hidden neuron */",
            tensor_to_c_array("SNN_W1", w1),
            "/* FC2 weights — [2 × HIDDEN]  linear output */",
            tensor_to_c_array("SNN_W2", w2),
        ]
    else:
        w1 = state["fc1.weight"]         # [HIDDEN, WINDOW]
        print(f"  Mode    : windowed")
        print(f"  W1 : {tuple(w1.shape)}   W2 : {tuple(w2.shape)}")
        print(f"  Beta1={beta1:.4f}  (no LIF2 — linear output layer)")
        print(f"  Flash footprint : {(w1.numel() + w2.numel()) * 4 / 1024:.1f} KB (float32)")
        lines = [
            "/* Auto-generated by export_weights.py — do NOT edit manually */",
            "#pragma once",
            "#include <stdint.h>",
            "",
            f"#define SNN_WINDOW       {cfg['window']}",
            f"#define SNN_HIDDEN       {w1.shape[0]}",
            f"#define SNN_T_STEPS      {cfg['t_steps']}",
            f"#define SNN_DELTA_THRESH {cfg['delta_thresh']:.4f}f",
            f"#define SNN_THRESH1      {cfg['threshold']:.4f}f",
            "",
            f"static const float SNN_BETA1 = {beta1:.6f}f;",
            "",
            "/* FC1 weights — [HIDDEN × WINDOW] */",
            tensor_to_c_array("SNN_W1", w1),
            "/* FC2 weights — [2 × HIDDEN]  linear output (no LIF2) */",
            tensor_to_c_array("SNN_W2", w2),
        ]

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Header written → {header_path}")


if __name__ == "__main__":
    main()
